services:
  php:
    container_name: php_blog_symfony
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/
      - ./phpunit.xml.dist:/var/www/phpunit.xml.dist
      - ./phpstan.neon:/var/www/phpstan.neon
  nginx:
    container_name: nginx_blog_symfony
    image: nginx:stable-alpine
    ports:
      - '8088:80'
    volumes:
      - ./:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
 